### Q1 Pandas version

In [45]:
import pandas as pd

pd.__version__

'2.3.3'

**Answer**: Pandas version in use is 2.3.3.

### Q2 Records count

In [46]:
df = pd.read_csv("../data/car_fuel_efficiency_2026.csv")
# First let's have a peek what we have in the file.
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [47]:
records = len(df)  # Prints number of records.
print(records)

10000


**Answer**: There is 10000 records in the csv file.

### Q3 Fuel types

In [48]:
fuel = df[
    "fuel_type"
].nunique()  # This print number of unique values in fuel_type column.
print(fuel)

3


**Answer**: There is three distinct values in the fuel types.

### Q4 Missing values

In [49]:
missing = df.isnull().sum()
print(missing)

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


**Answer**: Total amount of missing values is 1141, located in two distinct columns.

### Q5 Max fuel efficiency

In [50]:
# Fuel efficiency, cars from asia
cars_asia = df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"]

# Find the maximum value from the filtered data
max_asia = cars_asia.max()
print(max_asia)

41.2


**Answer**: Max fuel efficiency in a car made in Asia was approx 41,2.

### Q6 Median value of horsepower

In [51]:
# 1 median of horsepower
horsepow = df["horsepower"].median()
print(horsepow)

254.0


In [52]:
# 2 Find most frequent value in horsepower
frequent = df["horsepower"].mode()[0]
print(frequent)

252.0


In [53]:
# 3 Fill missing values with most frequent one
df["horsepower"] = df["horsepower"].fillna(frequent)

In [54]:
# 4 median of horsepower after filling
horsepow_filled = df["horsepower"].median()
print(horsepow_filled)

252.0


**Answer**: Has the value changed? Yes, it decreased.

### Q7 Sum of weights

In [55]:
# 1 Select all the cars from Asia
car_asia_all = df.loc[df["origin"] == "Asia"]
print(car_asia_all)

      model_year origin fuel_type         drivetrain  num_doors  \
2           1996   Asia  Gasoline  Front-wheel drive          5   
6           1992   Asia  Gasoline  Front-wheel drive          2   
8           1997   Asia  Gasoline   Rear-wheel drive          3   
10          1978   Asia  Gasoline    All-wheel drive          3   
15          2007   Asia    Diesel  Front-wheel drive          4   
...          ...    ...       ...                ...        ...   
9984        2011   Asia  Gasoline  Front-wheel drive          3   
9987        2004   Asia    Diesel    All-wheel drive          3   
9990        1975   Asia    Diesel  Front-wheel drive          4   
9994        1993   Asia  Gasoline   Rear-wheel drive          2   
9996        1993   Asia  Gasoline    All-wheel drive          2   

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
2                    2320              6       267.0            4240   
6                    2270              6       250.

In [56]:
# 2 Select only columns vehicle_weight and model_year
select_two = car_asia_all[["vehicle_weight", "model_year"]]
print(select_two)

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]


In [57]:
# 3 Select the first 7 values
select_two_seven = select_two.head(7)
print(select_two_seven)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019


In [58]:
# 4 Get the underlying NumPy array. Let's call it X.
X = select_two_seven.values
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [59]:
import numpy as np

np.__version__

'2.5.3'

In [60]:
# 5 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Get the transpose of X
X_T = X.T

# Compute the matrix-matrix multiplication XTX
XTX = np.matmul(X_T, X)

print(f"Transpose of X (X.T):\n{X_T}")
print(f"Matrix-matrix multiplication (XTX):\n{XTX}")

Transpose of X (X.T):
[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]
Matrix-matrix multiplication (XTX):
[[131950500  60750580]
 [ 60750580  28041424]]


In [61]:
# 6 Invert XTX.
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [62]:
# 7 Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [63]:
# 8 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# Multiply the inverse of XTX with the transpose of X
temp = np.matmul(XTX_inv, X_T)
print(temp)

# Multiply the result by y to get the weights
w = np.matmul(temp, y)
print(w)

[[-2.50082897e-04 -1.65786806e-05 -2.86196661e-04  3.99964853e-04
  -1.18162927e-03  1.10298508e-03  2.25354894e-04]
 [ 6.12974614e-04  1.06954785e-04  6.91249245e-04 -7.95968736e-04
   2.63152339e-03 -2.31749941e-03 -4.16221392e-04]]
[0.13644777 0.2327492 ]


In [64]:
# 9 What's the sum of all the elements of the result?
sum_w = np.sum(w)
print(sum_w)

0.36919696904925486


**Answer**: Sum is 0,369.